### PR TITLE
Scatter Plot for CTScans

### PR DESCRIPTION
**Pull request by perkyguy**
chart 1

I think this is a decent implementation. It's _only_ a scatter plot, which is strange that it took me this long just to do that, but it really shows the information nicely. The chart has the ability to cut out all inputs for a given output, or individual inputs. There are somethings which could probably be done nicer, but this is a good starting place.

Plus, it's "boosted", so you can load up 100,000 iterations in like 3 seconds. It's pretty nice.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
This looks fantastic.  I wonder though if there would be a way to distinguish each input from the others, that way you could see if the input was important to the net?

**Comment by robertleeplummerjr** [comment]
This looks to seperate: [](https://vooban.com/en/tips-articles-geek-stuff/hyperopt-tutorial-for-optimizing-neural-networks-hyperparameters/)

**Comment by robertleeplummerjr** [comment]
[](https://kmk-vu.github.io/posts/cnn)

**Comment by robertleeplummerjr** [comment]
[](https://rostlab.org/owiki/index.php/Snap2)

**Comment by robertleeplummerjr** [comment]
[ ](https://math.aalto.fi/~apiola/matlab/opas/TUUTOR11/html/plotting.html)

**Comment by robertleeplummerjr** [comment]
Checkout images of a "hinton diagram"

**Comment by robertleeplummerjr** [comment]
Note: this is just brainstorming, your work here is great

**Comment by robertleeplummerjr** [comment]
I wonder how this looks with a larger set of inputs?

**Comment by perkyguy** [comment]
Check out https://github.com/BrainJS/brain-ct.js/pull/3 , I did something similar to that first image you linked. 

chart 2

We could probably change the api a little though to do something like `translate.from(...).to.highchartsSync(data).hinton` or `translate.from(...).to.highchartsSync(data).scatter` ?

**Pull request merged**
